[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "modcord"
version = "0.0.1"
description = "A Discord bot for moderation using AI"
requires-python = "==3.12.*"
dependencies = []

[project.scripts]
modcord = "modcord.main:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]